---
# Semantic Type
- name: type/major
  color: "ededed"
- name: type/minor
  color: "ededed"
- name: type/patch
  color: "ededed"

# Uncategorized
- name: chore
  color: "E6CF9D"
  description: Work towards tech-debt
- name: bug
  color: "ee0701"
  description: Something isn't working
- name: do-not-merge
  color: "ee0701"
- name: link-checker
  color: "7B55D7"
- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation
- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists
- name: enhancement
  color: "a2eeef"
  description: New feature or request
- name: good first issue
  color: "7057ff"
  description: Good for newcomers
- name: help wanted
  color: "008672"
  description: Extra attention is needed
- name: invalid
  color: "e4e669"
  description: This doesn't seem right
- name: pipeline
  color: "79D905"
  description: Issue with CI/CD pipeline or workflow
- name: question
  color: "d876e3"
  description: Further information is requested
- name: security
  color: "006B75"
  description: Security Issue
- name: triage
  color: "D93F0B"
  description: Issue requires assessment
- name: triaged
  color: "c2e0c6"
  description: Issue has been triaged
- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: flux/upgrade
  color: "ededed"

# Renovate
- name: renovate/ansible
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/terraform
  color: "ffc300"
- name: renovate/annotations
  color: "ededed"

# Area
- name: area/local
  color: "72ccf3"
  description: >-
    Changes made in local tooling related files (e.g. .vscode)
- name: area/ci
  color: "72ccf3"
  description: >-
    Changes made in pipeline related files
- name: area/bot
  color: "72ccf3"
  description: >-
    Changes made in the core bot code
- name: area/docs
  color: "72ccf3"
  description: >-
    Changes made in documentation
- name: area/charts
  color: "72ccf3"
  description: >-
    Changes made in chart related files

# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.
