version: '3.7'

services:
  bloopyboi:
    image: ghcr.io/h3mmy/bloopyboi:latest
    container_name: bot
    # build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
