# IMPORTANT NOTE
# This chart inherits from the k8s@home library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
image:
  # -- image repository
  repository: registry.gitlab.com/h3mmy/bloopyboi
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v0.4.0@sha256:149a0f529c1fb25bb93ccf6e5de026ff1a1f3c1b6cc4d69580ede86792efc4a8

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  - name: TZ
    value: UTC
  # Downward API stuff. TODO move into template
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: POD_SERVICE_ACCOUNT
    valueFrom:
      fieldRef:
        fieldPath: spec.serviceAccountName

# -- Configures bot settings for this instance.
# @default -- See below
bloopyboi:
  # -- Discord Bot Credentials
  botName: BloopyBoi
  botToken: ""
  appId: ""

  # -- Log Level (info, warn, error, debug)
  logLevel: info

  # -- Feature Settings
  features:
      # -- Enables and configures InspiroBot
    - name: inspiro
      enabled: true
      data:
        - api_url: "https://inspirobot.me/api?generate=true"
        - backup_image_url: "https://generated.inspirobot.me/a/12PYMWaBPB.jpg"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

# -- Configures service account needed for k8s features
# @default -- See below
serviceAccount:
  # -- Create service account
  create: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
