// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/h3mmy/bloopyboi/bot/internal/ent/discordmessage"
	"gitlab.com/h3mmy/bloopyboi/bot/internal/ent/predicate"
)

// DiscordMessageDelete is the builder for deleting a DiscordMessage entity.
type DiscordMessageDelete struct {
	config
	hooks    []Hook
	mutation *DiscordMessageMutation
}

// Where appends a list predicates to the DiscordMessageDelete builder.
func (dmd *DiscordMessageDelete) Where(ps ...predicate.DiscordMessage) *DiscordMessageDelete {
	dmd.mutation.Where(ps...)
	return dmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dmd *DiscordMessageDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dmd.hooks) == 0 {
		affected, err = dmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiscordMessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dmd.mutation = mutation
			affected, err = dmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dmd.hooks) - 1; i >= 0; i-- {
			if dmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dmd *DiscordMessageDelete) ExecX(ctx context.Context) int {
	n, err := dmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dmd *DiscordMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: discordmessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: discordmessage.FieldID,
			},
		},
	}
	if ps := dmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// DiscordMessageDeleteOne is the builder for deleting a single DiscordMessage entity.
type DiscordMessageDeleteOne struct {
	dmd *DiscordMessageDelete
}

// Exec executes the deletion query.
func (dmdo *DiscordMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := dmdo.dmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dmdo *DiscordMessageDeleteOne) ExecX(ctx context.Context) {
	dmdo.dmd.ExecX(ctx)
}
