// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/h3mmy/bloopyboi/bot/internal/ent/discordmessage"
	"github.com/h3mmy/bloopyboi/bot/internal/ent/group"
	"github.com/h3mmy/bloopyboi/bot/internal/ent/schema"
	"github.com/h3mmy/bloopyboi/bot/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	discordmessageMixin := schema.DiscordMessage{}.Mixin()
	discordmessageMixinFields0 := discordmessageMixin[0].Fields()
	_ = discordmessageMixinFields0
	discordmessageFields := schema.DiscordMessage{}.Fields()
	_ = discordmessageFields
	// discordmessageDescCreateTime is the schema descriptor for create_time field.
	discordmessageDescCreateTime := discordmessageMixinFields0[0].Descriptor()
	// discordmessage.DefaultCreateTime holds the default value on creation for the create_time field.
	discordmessage.DefaultCreateTime = discordmessageDescCreateTime.Default.(func() time.Time)
	// discordmessageDescUpdateTime is the schema descriptor for update_time field.
	discordmessageDescUpdateTime := discordmessageMixinFields0[1].Descriptor()
	// discordmessage.DefaultUpdateTime holds the default value on creation for the update_time field.
	discordmessage.DefaultUpdateTime = discordmessageDescUpdateTime.Default.(func() time.Time)
	// discordmessage.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	discordmessage.UpdateDefaultUpdateTime = discordmessageDescUpdateTime.UpdateDefault.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDiscordid is the schema descriptor for discordid field.
	userDescDiscordid := userFields[1].Descriptor()
	// user.DefaultDiscordid holds the default value on creation for the discordid field.
	user.DefaultDiscordid = userDescDiscordid.Default.(string)
	// userDescPlexid is the schema descriptor for Plexid field.
	userDescPlexid := userFields[2].Descriptor()
	// user.DefaultPlexid holds the default value on creation for the Plexid field.
	user.DefaultPlexid = userDescPlexid.Default.(string)
}
