// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/h3mmy/bloopyboi/ent/book"
	"github.com/h3mmy/bloopyboi/ent/bookauthor"
	"github.com/h3mmy/bloopyboi/ent/mediarequest"
)

// BookCreate is the builder for creating a Book entity.
type BookCreate struct {
	config
	mutation *BookMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *BookCreate) SetTitle(v string) *BookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BookCreate) SetDescription(v string) *BookCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BookCreate) SetNillableDescription(v *string) *BookCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGoodreadsID sets the "goodreads_id" field.
func (_c *BookCreate) SetGoodreadsID(v string) *BookCreate {
	_c.mutation.SetGoodreadsID(v)
	return _c
}

// SetNillableGoodreadsID sets the "goodreads_id" field if the given value is not nil.
func (_c *BookCreate) SetNillableGoodreadsID(v *string) *BookCreate {
	if v != nil {
		_c.SetGoodreadsID(*v)
	}
	return _c
}

// SetGoogleVolumeID sets the "google_volume_id" field.
func (_c *BookCreate) SetGoogleVolumeID(v string) *BookCreate {
	_c.mutation.SetGoogleVolumeID(v)
	return _c
}

// SetIsbn10 sets the "isbn_10" field.
func (_c *BookCreate) SetIsbn10(v string) *BookCreate {
	_c.mutation.SetIsbn10(v)
	return _c
}

// SetNillableIsbn10 sets the "isbn_10" field if the given value is not nil.
func (_c *BookCreate) SetNillableIsbn10(v *string) *BookCreate {
	if v != nil {
		_c.SetIsbn10(*v)
	}
	return _c
}

// SetIsbn13 sets the "isbn_13" field.
func (_c *BookCreate) SetIsbn13(v string) *BookCreate {
	_c.mutation.SetIsbn13(v)
	return _c
}

// SetNillableIsbn13 sets the "isbn_13" field if the given value is not nil.
func (_c *BookCreate) SetNillableIsbn13(v *string) *BookCreate {
	if v != nil {
		_c.SetIsbn13(*v)
	}
	return _c
}

// SetPublisher sets the "publisher" field.
func (_c *BookCreate) SetPublisher(v string) *BookCreate {
	_c.mutation.SetPublisher(v)
	return _c
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_c *BookCreate) SetNillablePublisher(v *string) *BookCreate {
	if v != nil {
		_c.SetPublisher(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *BookCreate) SetImageURL(v string) *BookCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *BookCreate) SetNillableImageURL(v *string) *BookCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BookCreate) SetID(v uuid.UUID) *BookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BookCreate) SetNillableID(v *uuid.UUID) *BookCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBookAuthorIDs adds the "book_author" edge to the BookAuthor entity by IDs.
func (_c *BookCreate) AddBookAuthorIDs(ids ...uuid.UUID) *BookCreate {
	_c.mutation.AddBookAuthorIDs(ids...)
	return _c
}

// AddBookAuthor adds the "book_author" edges to the BookAuthor entity.
func (_c *BookCreate) AddBookAuthor(v ...*BookAuthor) *BookCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookAuthorIDs(ids...)
}

// SetMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID.
func (_c *BookCreate) SetMediaRequestID(id uuid.UUID) *BookCreate {
	_c.mutation.SetMediaRequestID(id)
	return _c
}

// SetNillableMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID if the given value is not nil.
func (_c *BookCreate) SetNillableMediaRequestID(id *uuid.UUID) *BookCreate {
	if id != nil {
		_c = _c.SetMediaRequestID(*id)
	}
	return _c
}

// SetMediaRequest sets the "media_request" edge to the MediaRequest entity.
func (_c *BookCreate) SetMediaRequest(v *MediaRequest) *BookCreate {
	return _c.SetMediaRequestID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_c *BookCreate) Mutation() *BookMutation {
	return _c.mutation
}

// Save creates the Book in the database.
func (_c *BookCreate) Save(ctx context.Context) (*Book, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookCreate) SaveX(ctx context.Context) *Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := book.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Book.title"`)}
	}
	if _, ok := _c.mutation.GoogleVolumeID(); !ok {
		return &ValidationError{Name: "google_volume_id", err: errors.New(`ent: missing required field "Book.google_volume_id"`)}
	}
	return nil
}

func (_c *BookCreate) sqlSave(ctx context.Context) (*Book, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookCreate) createSpec() (*Book, *sqlgraph.CreateSpec) {
	var (
		_node = &Book{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(book.Table, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.GoodreadsID(); ok {
		_spec.SetField(book.FieldGoodreadsID, field.TypeString, value)
		_node.GoodreadsID = value
	}
	if value, ok := _c.mutation.GoogleVolumeID(); ok {
		_spec.SetField(book.FieldGoogleVolumeID, field.TypeString, value)
		_node.GoogleVolumeID = value
	}
	if value, ok := _c.mutation.Isbn10(); ok {
		_spec.SetField(book.FieldIsbn10, field.TypeString, value)
		_node.Isbn10 = value
	}
	if value, ok := _c.mutation.Isbn13(); ok {
		_spec.SetField(book.FieldIsbn13, field.TypeString, value)
		_node.Isbn13 = value
	}
	if value, ok := _c.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
		_node.Publisher = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(book.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if nodes := _c.mutation.BookAuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MediaRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   book.MediaRequestTable,
			Columns: []string{book.MediaRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediarequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BookCreateBulk is the builder for creating many Book entities in bulk.
type BookCreateBulk struct {
	config
	err      error
	builders []*BookCreate
}

// Save creates the Book entities in the database.
func (_c *BookCreateBulk) Save(ctx context.Context) ([]*Book, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Book, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookCreateBulk) SaveX(ctx context.Context) []*Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
