// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/h3mmy/bloopyboi/ent/book"
	"github.com/h3mmy/bloopyboi/ent/bookauthor"
	"github.com/h3mmy/bloopyboi/ent/mediarequest"
	"github.com/h3mmy/bloopyboi/ent/predicate"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdate) SetDescription(v string) *BookUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdate) SetNillableDescription(v *string) *BookUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdate) ClearDescription() *BookUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGoodreadsID sets the "goodreads_id" field.
func (_u *BookUpdate) SetGoodreadsID(v string) *BookUpdate {
	_u.mutation.SetGoodreadsID(v)
	return _u
}

// SetNillableGoodreadsID sets the "goodreads_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableGoodreadsID(v *string) *BookUpdate {
	if v != nil {
		_u.SetGoodreadsID(*v)
	}
	return _u
}

// ClearGoodreadsID clears the value of the "goodreads_id" field.
func (_u *BookUpdate) ClearGoodreadsID() *BookUpdate {
	_u.mutation.ClearGoodreadsID()
	return _u
}

// SetGoogleVolumeID sets the "google_volume_id" field.
func (_u *BookUpdate) SetGoogleVolumeID(v string) *BookUpdate {
	_u.mutation.SetGoogleVolumeID(v)
	return _u
}

// SetNillableGoogleVolumeID sets the "google_volume_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableGoogleVolumeID(v *string) *BookUpdate {
	if v != nil {
		_u.SetGoogleVolumeID(*v)
	}
	return _u
}

// SetIsbn10 sets the "isbn_10" field.
func (_u *BookUpdate) SetIsbn10(v string) *BookUpdate {
	_u.mutation.SetIsbn10(v)
	return _u
}

// SetNillableIsbn10 sets the "isbn_10" field if the given value is not nil.
func (_u *BookUpdate) SetNillableIsbn10(v *string) *BookUpdate {
	if v != nil {
		_u.SetIsbn10(*v)
	}
	return _u
}

// ClearIsbn10 clears the value of the "isbn_10" field.
func (_u *BookUpdate) ClearIsbn10() *BookUpdate {
	_u.mutation.ClearIsbn10()
	return _u
}

// SetIsbn13 sets the "isbn_13" field.
func (_u *BookUpdate) SetIsbn13(v string) *BookUpdate {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn_13" field if the given value is not nil.
func (_u *BookUpdate) SetNillableIsbn13(v *string) *BookUpdate {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn_13" field.
func (_u *BookUpdate) ClearIsbn13() *BookUpdate {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookUpdate) SetPublisher(v string) *BookUpdate {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePublisher(v *string) *BookUpdate {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// ClearPublisher clears the value of the "publisher" field.
func (_u *BookUpdate) ClearPublisher() *BookUpdate {
	_u.mutation.ClearPublisher()
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *BookUpdate) SetImageURL(v string) *BookUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableImageURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *BookUpdate) ClearImageURL() *BookUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// AddBookAuthorIDs adds the "book_author" edge to the BookAuthor entity by IDs.
func (_u *BookUpdate) AddBookAuthorIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddBookAuthorIDs(ids...)
	return _u
}

// AddBookAuthor adds the "book_author" edges to the BookAuthor entity.
func (_u *BookUpdate) AddBookAuthor(v ...*BookAuthor) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookAuthorIDs(ids...)
}

// SetMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID.
func (_u *BookUpdate) SetMediaRequestID(id uuid.UUID) *BookUpdate {
	_u.mutation.SetMediaRequestID(id)
	return _u
}

// SetNillableMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID if the given value is not nil.
func (_u *BookUpdate) SetNillableMediaRequestID(id *uuid.UUID) *BookUpdate {
	if id != nil {
		_u = _u.SetMediaRequestID(*id)
	}
	return _u
}

// SetMediaRequest sets the "media_request" edge to the MediaRequest entity.
func (_u *BookUpdate) SetMediaRequest(v *MediaRequest) *BookUpdate {
	return _u.SetMediaRequestID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearBookAuthor clears all "book_author" edges to the BookAuthor entity.
func (_u *BookUpdate) ClearBookAuthor() *BookUpdate {
	_u.mutation.ClearBookAuthor()
	return _u
}

// RemoveBookAuthorIDs removes the "book_author" edge to BookAuthor entities by IDs.
func (_u *BookUpdate) RemoveBookAuthorIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveBookAuthorIDs(ids...)
	return _u
}

// RemoveBookAuthor removes "book_author" edges to BookAuthor entities.
func (_u *BookUpdate) RemoveBookAuthor(v ...*BookAuthor) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookAuthorIDs(ids...)
}

// ClearMediaRequest clears the "media_request" edge to the MediaRequest entity.
func (_u *BookUpdate) ClearMediaRequest() *BookUpdate {
	_u.mutation.ClearMediaRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GoodreadsID(); ok {
		_spec.SetField(book.FieldGoodreadsID, field.TypeString, value)
	}
	if _u.mutation.GoodreadsIDCleared() {
		_spec.ClearField(book.FieldGoodreadsID, field.TypeString)
	}
	if value, ok := _u.mutation.GoogleVolumeID(); ok {
		_spec.SetField(book.FieldGoogleVolumeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn10(); ok {
		_spec.SetField(book.FieldIsbn10, field.TypeString, value)
	}
	if _u.mutation.Isbn10Cleared() {
		_spec.ClearField(book.FieldIsbn10, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(book.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(book.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if _u.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(book.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(book.FieldImageURL, field.TypeString)
	}
	if _u.mutation.BookAuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookAuthorIDs(); len(nodes) > 0 && !_u.mutation.BookAuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookAuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MediaRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   book.MediaRequestTable,
			Columns: []string{book.MediaRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediarequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   book.MediaRequestTable,
			Columns: []string{book.MediaRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediarequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdateOne) SetDescription(v string) *BookUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableDescription(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdateOne) ClearDescription() *BookUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGoodreadsID sets the "goodreads_id" field.
func (_u *BookUpdateOne) SetGoodreadsID(v string) *BookUpdateOne {
	_u.mutation.SetGoodreadsID(v)
	return _u
}

// SetNillableGoodreadsID sets the "goodreads_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableGoodreadsID(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetGoodreadsID(*v)
	}
	return _u
}

// ClearGoodreadsID clears the value of the "goodreads_id" field.
func (_u *BookUpdateOne) ClearGoodreadsID() *BookUpdateOne {
	_u.mutation.ClearGoodreadsID()
	return _u
}

// SetGoogleVolumeID sets the "google_volume_id" field.
func (_u *BookUpdateOne) SetGoogleVolumeID(v string) *BookUpdateOne {
	_u.mutation.SetGoogleVolumeID(v)
	return _u
}

// SetNillableGoogleVolumeID sets the "google_volume_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableGoogleVolumeID(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetGoogleVolumeID(*v)
	}
	return _u
}

// SetIsbn10 sets the "isbn_10" field.
func (_u *BookUpdateOne) SetIsbn10(v string) *BookUpdateOne {
	_u.mutation.SetIsbn10(v)
	return _u
}

// SetNillableIsbn10 sets the "isbn_10" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableIsbn10(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetIsbn10(*v)
	}
	return _u
}

// ClearIsbn10 clears the value of the "isbn_10" field.
func (_u *BookUpdateOne) ClearIsbn10() *BookUpdateOne {
	_u.mutation.ClearIsbn10()
	return _u
}

// SetIsbn13 sets the "isbn_13" field.
func (_u *BookUpdateOne) SetIsbn13(v string) *BookUpdateOne {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn_13" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableIsbn13(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn_13" field.
func (_u *BookUpdateOne) ClearIsbn13() *BookUpdateOne {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookUpdateOne) SetPublisher(v string) *BookUpdateOne {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePublisher(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// ClearPublisher clears the value of the "publisher" field.
func (_u *BookUpdateOne) ClearPublisher() *BookUpdateOne {
	_u.mutation.ClearPublisher()
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *BookUpdateOne) SetImageURL(v string) *BookUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableImageURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *BookUpdateOne) ClearImageURL() *BookUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// AddBookAuthorIDs adds the "book_author" edge to the BookAuthor entity by IDs.
func (_u *BookUpdateOne) AddBookAuthorIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddBookAuthorIDs(ids...)
	return _u
}

// AddBookAuthor adds the "book_author" edges to the BookAuthor entity.
func (_u *BookUpdateOne) AddBookAuthor(v ...*BookAuthor) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookAuthorIDs(ids...)
}

// SetMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID.
func (_u *BookUpdateOne) SetMediaRequestID(id uuid.UUID) *BookUpdateOne {
	_u.mutation.SetMediaRequestID(id)
	return _u
}

// SetNillableMediaRequestID sets the "media_request" edge to the MediaRequest entity by ID if the given value is not nil.
func (_u *BookUpdateOne) SetNillableMediaRequestID(id *uuid.UUID) *BookUpdateOne {
	if id != nil {
		_u = _u.SetMediaRequestID(*id)
	}
	return _u
}

// SetMediaRequest sets the "media_request" edge to the MediaRequest entity.
func (_u *BookUpdateOne) SetMediaRequest(v *MediaRequest) *BookUpdateOne {
	return _u.SetMediaRequestID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearBookAuthor clears all "book_author" edges to the BookAuthor entity.
func (_u *BookUpdateOne) ClearBookAuthor() *BookUpdateOne {
	_u.mutation.ClearBookAuthor()
	return _u
}

// RemoveBookAuthorIDs removes the "book_author" edge to BookAuthor entities by IDs.
func (_u *BookUpdateOne) RemoveBookAuthorIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveBookAuthorIDs(ids...)
	return _u
}

// RemoveBookAuthor removes "book_author" edges to BookAuthor entities.
func (_u *BookUpdateOne) RemoveBookAuthor(v ...*BookAuthor) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookAuthorIDs(ids...)
}

// ClearMediaRequest clears the "media_request" edge to the MediaRequest entity.
func (_u *BookUpdateOne) ClearMediaRequest() *BookUpdateOne {
	_u.mutation.ClearMediaRequest()
	return _u
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GoodreadsID(); ok {
		_spec.SetField(book.FieldGoodreadsID, field.TypeString, value)
	}
	if _u.mutation.GoodreadsIDCleared() {
		_spec.ClearField(book.FieldGoodreadsID, field.TypeString)
	}
	if value, ok := _u.mutation.GoogleVolumeID(); ok {
		_spec.SetField(book.FieldGoogleVolumeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn10(); ok {
		_spec.SetField(book.FieldIsbn10, field.TypeString, value)
	}
	if _u.mutation.Isbn10Cleared() {
		_spec.ClearField(book.FieldIsbn10, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(book.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(book.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if _u.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(book.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(book.FieldImageURL, field.TypeString)
	}
	if _u.mutation.BookAuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookAuthorIDs(); len(nodes) > 0 && !_u.mutation.BookAuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookAuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.BookAuthorTable,
			Columns: book.BookAuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MediaRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   book.MediaRequestTable,
			Columns: []string{book.MediaRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediarequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   book.MediaRequestTable,
			Columns: []string{book.MediaRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediarequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
