// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/h3mmy/bloopyboi/ent/discordchannel"
	"github.com/h3mmy/bloopyboi/ent/discordguild"
	"github.com/h3mmy/bloopyboi/ent/discordmessage"
	"github.com/h3mmy/bloopyboi/ent/discorduser"
)

// DiscordGuildCreate is the builder for creating a DiscordGuild entity.
type DiscordGuildCreate struct {
	config
	mutation *DiscordGuildMutation
	hooks    []Hook
}

// SetDiscordid sets the "discordid" field.
func (_c *DiscordGuildCreate) SetDiscordid(v string) *DiscordGuildCreate {
	_c.mutation.SetDiscordid(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DiscordGuildCreate) SetName(v string) *DiscordGuildCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DiscordGuildCreate) SetDescription(v string) *DiscordGuildCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DiscordGuildCreate) SetNillableDescription(v *string) *DiscordGuildCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRulesChannelID sets the "rules_channel_id" field.
func (_c *DiscordGuildCreate) SetRulesChannelID(v string) *DiscordGuildCreate {
	_c.mutation.SetRulesChannelID(v)
	return _c
}

// SetNillableRulesChannelID sets the "rules_channel_id" field if the given value is not nil.
func (_c *DiscordGuildCreate) SetNillableRulesChannelID(v *string) *DiscordGuildCreate {
	if v != nil {
		_c.SetRulesChannelID(*v)
	}
	return _c
}

// SetPublicUpdatesChannelID sets the "public_updates_channel_id" field.
func (_c *DiscordGuildCreate) SetPublicUpdatesChannelID(v string) *DiscordGuildCreate {
	_c.mutation.SetPublicUpdatesChannelID(v)
	return _c
}

// SetNillablePublicUpdatesChannelID sets the "public_updates_channel_id" field if the given value is not nil.
func (_c *DiscordGuildCreate) SetNillablePublicUpdatesChannelID(v *string) *DiscordGuildCreate {
	if v != nil {
		_c.SetPublicUpdatesChannelID(*v)
	}
	return _c
}

// SetNsfwLevel sets the "nsfw_level" field.
func (_c *DiscordGuildCreate) SetNsfwLevel(v int) *DiscordGuildCreate {
	_c.mutation.SetNsfwLevel(v)
	return _c
}

// SetNillableNsfwLevel sets the "nsfw_level" field if the given value is not nil.
func (_c *DiscordGuildCreate) SetNillableNsfwLevel(v *int) *DiscordGuildCreate {
	if v != nil {
		_c.SetNsfwLevel(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordGuildCreate) SetID(v uuid.UUID) *DiscordGuildCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DiscordGuildCreate) SetNillableID(v *uuid.UUID) *DiscordGuildCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the DiscordUser entity by IDs.
func (_c *DiscordGuildCreate) AddMemberIDs(ids ...uuid.UUID) *DiscordGuildCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the DiscordUser entity.
func (_c *DiscordGuildCreate) AddMembers(v ...*DiscordUser) *DiscordGuildCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddDiscordMessageIDs adds the "discord_messages" edge to the DiscordMessage entity by IDs.
func (_c *DiscordGuildCreate) AddDiscordMessageIDs(ids ...uuid.UUID) *DiscordGuildCreate {
	_c.mutation.AddDiscordMessageIDs(ids...)
	return _c
}

// AddDiscordMessages adds the "discord_messages" edges to the DiscordMessage entity.
func (_c *DiscordGuildCreate) AddDiscordMessages(v ...*DiscordMessage) *DiscordGuildCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDiscordMessageIDs(ids...)
}

// AddGuildChannelIDs adds the "guild_channels" edge to the DiscordChannel entity by IDs.
func (_c *DiscordGuildCreate) AddGuildChannelIDs(ids ...uuid.UUID) *DiscordGuildCreate {
	_c.mutation.AddGuildChannelIDs(ids...)
	return _c
}

// AddGuildChannels adds the "guild_channels" edges to the DiscordChannel entity.
func (_c *DiscordGuildCreate) AddGuildChannels(v ...*DiscordChannel) *DiscordGuildCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGuildChannelIDs(ids...)
}

// Mutation returns the DiscordGuildMutation object of the builder.
func (_c *DiscordGuildCreate) Mutation() *DiscordGuildMutation {
	return _c.mutation
}

// Save creates the DiscordGuild in the database.
func (_c *DiscordGuildCreate) Save(ctx context.Context) (*DiscordGuild, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordGuildCreate) SaveX(ctx context.Context) *DiscordGuild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordGuildCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordGuildCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscordGuildCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := discordguild.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordGuildCreate) check() error {
	if _, ok := _c.mutation.Discordid(); !ok {
		return &ValidationError{Name: "discordid", err: errors.New(`ent: missing required field "DiscordGuild.discordid"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DiscordGuild.name"`)}
	}
	return nil
}

func (_c *DiscordGuildCreate) sqlSave(ctx context.Context) (*DiscordGuild, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordGuildCreate) createSpec() (*DiscordGuild, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordGuild{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discordguild.Table, sqlgraph.NewFieldSpec(discordguild.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Discordid(); ok {
		_spec.SetField(discordguild.FieldDiscordid, field.TypeString, value)
		_node.Discordid = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(discordguild.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(discordguild.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RulesChannelID(); ok {
		_spec.SetField(discordguild.FieldRulesChannelID, field.TypeString, value)
		_node.RulesChannelID = value
	}
	if value, ok := _c.mutation.PublicUpdatesChannelID(); ok {
		_spec.SetField(discordguild.FieldPublicUpdatesChannelID, field.TypeString, value)
		_node.PublicUpdatesChannelID = value
	}
	if value, ok := _c.mutation.NsfwLevel(); ok {
		_spec.SetField(discordguild.FieldNsfwLevel, field.TypeInt, value)
		_node.NsfwLevel = value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   discordguild.MembersTable,
			Columns: discordguild.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiscordMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordguild.DiscordMessagesTable,
			Columns: []string{discordguild.DiscordMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GuildChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   discordguild.GuildChannelsTable,
			Columns: discordguild.GuildChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiscordGuildCreateBulk is the builder for creating many DiscordGuild entities in bulk.
type DiscordGuildCreateBulk struct {
	config
	err      error
	builders []*DiscordGuildCreate
}

// Save creates the DiscordGuild entities in the database.
func (_c *DiscordGuildCreateBulk) Save(ctx context.Context) ([]*DiscordGuild, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordGuild, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordGuildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordGuildCreateBulk) SaveX(ctx context.Context) []*DiscordGuild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordGuildCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordGuildCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
