// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bwmarrin/discordgo"
	"github.com/google/uuid"
	"github.com/h3mmy/bloopyboi/ent/discordmessage"
	"github.com/h3mmy/bloopyboi/ent/discorduser"
	"github.com/h3mmy/bloopyboi/ent/predicate"
)

// DiscordMessageUpdate is the builder for updating DiscordMessage entities.
type DiscordMessageUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordMessageMutation
}

// Where appends a list predicates to the DiscordMessageUpdate builder.
func (dmu *DiscordMessageUpdate) Where(ps ...predicate.DiscordMessage) *DiscordMessageUpdate {
	dmu.mutation.Where(ps...)
	return dmu
}

// SetUpdateTime sets the "update_time" field.
func (dmu *DiscordMessageUpdate) SetUpdateTime(t time.Time) *DiscordMessageUpdate {
	dmu.mutation.SetUpdateTime(t)
	return dmu
}

// SetRaw sets the "raw" field.
func (dmu *DiscordMessageUpdate) SetRaw(d discordgo.Message) *DiscordMessageUpdate {
	dmu.mutation.SetRaw(d)
	return dmu
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (dmu *DiscordMessageUpdate) SetNillableRaw(d *discordgo.Message) *DiscordMessageUpdate {
	if d != nil {
		dmu.SetRaw(*d)
	}
	return dmu
}

// AddAuthorIDs adds the "author" edge to the DiscordUser entity by IDs.
func (dmu *DiscordMessageUpdate) AddAuthorIDs(ids ...uuid.UUID) *DiscordMessageUpdate {
	dmu.mutation.AddAuthorIDs(ids...)
	return dmu
}

// AddAuthor adds the "author" edges to the DiscordUser entity.
func (dmu *DiscordMessageUpdate) AddAuthor(d ...*DiscordUser) *DiscordMessageUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dmu.AddAuthorIDs(ids...)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (dmu *DiscordMessageUpdate) Mutation() *DiscordMessageMutation {
	return dmu.mutation
}

// ClearAuthor clears all "author" edges to the DiscordUser entity.
func (dmu *DiscordMessageUpdate) ClearAuthor() *DiscordMessageUpdate {
	dmu.mutation.ClearAuthor()
	return dmu
}

// RemoveAuthorIDs removes the "author" edge to DiscordUser entities by IDs.
func (dmu *DiscordMessageUpdate) RemoveAuthorIDs(ids ...uuid.UUID) *DiscordMessageUpdate {
	dmu.mutation.RemoveAuthorIDs(ids...)
	return dmu
}

// RemoveAuthor removes "author" edges to DiscordUser entities.
func (dmu *DiscordMessageUpdate) RemoveAuthor(d ...*DiscordUser) *DiscordMessageUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dmu.RemoveAuthorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dmu *DiscordMessageUpdate) Save(ctx context.Context) (int, error) {
	dmu.defaults()
	return withHooks(ctx, dmu.sqlSave, dmu.mutation, dmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dmu *DiscordMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := dmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dmu *DiscordMessageUpdate) Exec(ctx context.Context) error {
	_, err := dmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dmu *DiscordMessageUpdate) ExecX(ctx context.Context) {
	if err := dmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dmu *DiscordMessageUpdate) defaults() {
	if _, ok := dmu.mutation.UpdateTime(); !ok {
		v := discordmessage.UpdateDefaultUpdateTime()
		dmu.mutation.SetUpdateTime(v)
	}
}

func (dmu *DiscordMessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(discordmessage.Table, discordmessage.Columns, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	if ps := dmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dmu.mutation.UpdateTime(); ok {
		_spec.SetField(discordmessage.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := dmu.mutation.Raw(); ok {
		_spec.SetField(discordmessage.FieldRaw, field.TypeJSON, value)
	}
	if dmu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dmu.mutation.RemovedAuthorIDs(); len(nodes) > 0 && !dmu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dmu.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dmu.mutation.done = true
	return n, nil
}

// DiscordMessageUpdateOne is the builder for updating a single DiscordMessage entity.
type DiscordMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordMessageMutation
}

// SetUpdateTime sets the "update_time" field.
func (dmuo *DiscordMessageUpdateOne) SetUpdateTime(t time.Time) *DiscordMessageUpdateOne {
	dmuo.mutation.SetUpdateTime(t)
	return dmuo
}

// SetRaw sets the "raw" field.
func (dmuo *DiscordMessageUpdateOne) SetRaw(d discordgo.Message) *DiscordMessageUpdateOne {
	dmuo.mutation.SetRaw(d)
	return dmuo
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (dmuo *DiscordMessageUpdateOne) SetNillableRaw(d *discordgo.Message) *DiscordMessageUpdateOne {
	if d != nil {
		dmuo.SetRaw(*d)
	}
	return dmuo
}

// AddAuthorIDs adds the "author" edge to the DiscordUser entity by IDs.
func (dmuo *DiscordMessageUpdateOne) AddAuthorIDs(ids ...uuid.UUID) *DiscordMessageUpdateOne {
	dmuo.mutation.AddAuthorIDs(ids...)
	return dmuo
}

// AddAuthor adds the "author" edges to the DiscordUser entity.
func (dmuo *DiscordMessageUpdateOne) AddAuthor(d ...*DiscordUser) *DiscordMessageUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dmuo.AddAuthorIDs(ids...)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (dmuo *DiscordMessageUpdateOne) Mutation() *DiscordMessageMutation {
	return dmuo.mutation
}

// ClearAuthor clears all "author" edges to the DiscordUser entity.
func (dmuo *DiscordMessageUpdateOne) ClearAuthor() *DiscordMessageUpdateOne {
	dmuo.mutation.ClearAuthor()
	return dmuo
}

// RemoveAuthorIDs removes the "author" edge to DiscordUser entities by IDs.
func (dmuo *DiscordMessageUpdateOne) RemoveAuthorIDs(ids ...uuid.UUID) *DiscordMessageUpdateOne {
	dmuo.mutation.RemoveAuthorIDs(ids...)
	return dmuo
}

// RemoveAuthor removes "author" edges to DiscordUser entities.
func (dmuo *DiscordMessageUpdateOne) RemoveAuthor(d ...*DiscordUser) *DiscordMessageUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dmuo.RemoveAuthorIDs(ids...)
}

// Where appends a list predicates to the DiscordMessageUpdate builder.
func (dmuo *DiscordMessageUpdateOne) Where(ps ...predicate.DiscordMessage) *DiscordMessageUpdateOne {
	dmuo.mutation.Where(ps...)
	return dmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dmuo *DiscordMessageUpdateOne) Select(field string, fields ...string) *DiscordMessageUpdateOne {
	dmuo.fields = append([]string{field}, fields...)
	return dmuo
}

// Save executes the query and returns the updated DiscordMessage entity.
func (dmuo *DiscordMessageUpdateOne) Save(ctx context.Context) (*DiscordMessage, error) {
	dmuo.defaults()
	return withHooks(ctx, dmuo.sqlSave, dmuo.mutation, dmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dmuo *DiscordMessageUpdateOne) SaveX(ctx context.Context) *DiscordMessage {
	node, err := dmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dmuo *DiscordMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := dmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dmuo *DiscordMessageUpdateOne) ExecX(ctx context.Context) {
	if err := dmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dmuo *DiscordMessageUpdateOne) defaults() {
	if _, ok := dmuo.mutation.UpdateTime(); !ok {
		v := discordmessage.UpdateDefaultUpdateTime()
		dmuo.mutation.SetUpdateTime(v)
	}
}

func (dmuo *DiscordMessageUpdateOne) sqlSave(ctx context.Context) (_node *DiscordMessage, err error) {
	_spec := sqlgraph.NewUpdateSpec(discordmessage.Table, discordmessage.Columns, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	id, ok := dmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordmessage.FieldID)
		for _, f := range fields {
			if !discordmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discordmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dmuo.mutation.UpdateTime(); ok {
		_spec.SetField(discordmessage.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := dmuo.mutation.Raw(); ok {
		_spec.SetField(discordmessage.FieldRaw, field.TypeJSON, value)
	}
	if dmuo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dmuo.mutation.RemovedAuthorIDs(); len(nodes) > 0 && !dmuo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dmuo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   discordmessage.AuthorTable,
			Columns: discordmessage.AuthorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiscordMessage{config: dmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dmuo.mutation.done = true
	return _node, nil
}
