// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/h3mmy/bloopyboi/ent/emojikeywordscore"
	"github.com/h3mmy/bloopyboi/ent/predicate"
)

// EmojiKeywordScoreDelete is the builder for deleting a EmojiKeywordScore entity.
type EmojiKeywordScoreDelete struct {
	config
	hooks    []Hook
	mutation *EmojiKeywordScoreMutation
}

// Where appends a list predicates to the EmojiKeywordScoreDelete builder.
func (_d *EmojiKeywordScoreDelete) Where(ps ...predicate.EmojiKeywordScore) *EmojiKeywordScoreDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EmojiKeywordScoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmojiKeywordScoreDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EmojiKeywordScoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emojikeywordscore.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EmojiKeywordScoreDeleteOne is the builder for deleting a single EmojiKeywordScore entity.
type EmojiKeywordScoreDeleteOne struct {
	_d *EmojiKeywordScoreDelete
}

// Where appends a list predicates to the EmojiKeywordScoreDelete builder.
func (_d *EmojiKeywordScoreDeleteOne) Where(ps ...predicate.EmojiKeywordScore) *EmojiKeywordScoreDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EmojiKeywordScoreDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emojikeywordscore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmojiKeywordScoreDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
