---
run:
  timeout: 3m
formatters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    # - unused
linters:
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
