---
run:
  timeout: 3m
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    # - typecheck
    # - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
