---
name: Lint
description: Runs golangci-lint on the project

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ">=1.21"

    # Run golangcilint before `go get` is ran
    # https://github.com/golangci/golangci-lint-action/issues/23
    - uses: golangci/golangci-lint-action@v9
      with:
        version: v2.1
        args: --timeout 5m --config .github/lint/golangci.yaml
