---
name: Deploy BloopyBoi to Neutrino

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './app/*'
      - './requirements.txt'
      - './Dockerfile'
      - './docker-compose.yml'

jobs:

  run-unit-tests:
    uses: ./.github/workflows/python-app.yml

  build-and-deploy-image:
    needs: run-unit-tests
    uses: ./.github/workflows/deploy-image.yaml

  deployment:
    environment: quarkynet
    needs: build-and-deploy-image
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/remote-docker-up.yaml
        with:
          envPAT: ${{ secrets.GITHUB_TOKEN }}
          sshKey: ${{ secrets.NEUTRINO_SSH_KEY }}
          remoteHost: ${{ secrets.HOST_0_NAME }}
          remoteUser: ${{ secrets.NEUTRINO_USER_NAME }}
          remoteDir: ${{ secrets.DOCKER_REMOTE_DIR }}
          discordBotToken: ${{ secrets.DISCORD_BOT_TOKEN }}
