---
name: Deploy BloopyBoi to Neutrino

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:

  Run Unit Tests:
    uses: h3mmy/bloopyboi/.github/workflows/python-app.yml@main

  Build and Deploy Image:
    uses: h3mmy/bloopyboi/.github/workflows/deploy-image.yaml@main

  Deploy to Node:
    uses: h3mmy/bloopyboi/.github/workflows/remote-docker-up.yaml@main
    with:
      environment: quarkynet
