---
name: Deploy BloopyBoi to GHCR

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/*

env:
  registry: ghcr.io
  imageName: bloopyboi
  dockerfile_path: ./Dockerfile

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.dockerfile_path }}
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.imageName }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.imageName }}:latest
