---
name: Deploy BloopyBoi to Neutrino

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './app/*'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-compose.yml'

jobs:

  run-unit-tests:
    uses: h3mmy/bloopyboi/.github/workflows/python-app.yml@main

  build-and-deploy-image:
    uses: h3mmy/bloopyboi/.github/workflows/deploy-image.yaml@main

  deploy-to-node:
    depends-on: build-and-deploy-image
    uses: h3mmy/bloopyboi/.github/workflows/remote-docker-up.yaml@main
    with:
      environment: quarkynet
