# This is a basic workflow that is manually triggered

name: Deploy to Camelus via SSH

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy_to_server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Copying files and artifacts via SSH
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BLOOPNET_SSH_KEY }}" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        eval `ssh-agent -s`
        ssh-add ~/.ssh/staging.key
        echo "${{ secrets.BLOOPNET_HOST_KEY_PUB }}" > ~/.ssh/known_hosts
        cat >>~/.ssh/config <<END
        Host staging
          HostName ${{ secrets.BLOOPNET_HOST_NAME }}
          User ${{ secrets.BLOOPNET_GIT_USER }}
          IdentityFile ~/.ssh/staging.key
          Port ${{ secrets.BLOOPNET_SSH_PORT }}
        END
      env:
        SSH_ASKPASS: ${{ secrets.BLOOPNET_SSH_KEY_PASSPHRASE }}
        
    - name: SSH into server
      run: |
        ssh -vvv staging whoami
