---
name: Deploy BloopyBoi to Neutrino

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './app/*'
      - './requirements.txt'
      - './Dockerfile'
      - './docker-compose.yml'

env:
  environment: quarkynet

jobs:

  run-unit-tests:
    uses: ./.github/workflows/python-app.yml@main

  build-and-deploy-image:
    needs: run-unit-tests
    uses: ./.github/workflows/deploy-image.yaml@main

  deployment:
    needs: build-and-deploy-image
    uses: ./.github/workflows/remote-docker-up.yaml@main
    with:
      environment: ${{ env.environment }}
