---
# yamllint disable rule:line-length

name: Automatically add issues to project tracking board

on:  # yamllint disable-line rule:truthy
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project board
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1.9.0
        id: generate-token
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.APP_PRIVATE_KEY }}"
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@0609a2702eefb44781da00f8e04901d6e5cd2b92 # v0.6.0
        with:
          project-url: https://github.com/users/h3mmy/projects/3
          # PAT needs repo & project scope
          github-token: ${{ steps.generate-token.outputs.token }}
