name: Bot Deployment

# Disabling this as host is now invalid
on:
  workflow_dispatch:
  # Need to rewrite for reusability
  workflow_call:

jobs:
  deploy_to_server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checkout repo to runner
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.DEPLOY_PAT }}
    # Copying files and artifacts via SSH
    - name: Configure SSH and create staging files
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MINI_BLOOP_SSH_KEY }}" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        ssh-keyscan ${{ secrets.MINI_BLOOP_HOST_NAME }} | tee -a ~/.ssh/known_hosts
        echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" > .env
        cat >>~/.ssh/config <<END
        Host staging
          HostName ${{ secrets.MINI_BLOOP_HOST_NAME }}
          User ${{ secrets.MINI_BLOOP_SSH_USER }}
          IdentityFile ~/.ssh/staging.key
        END

    - name: Update agent copy of repo
      run: |
        ssh staging 'cd ${{ secrets.MINI_BLOOP_REMOTE_DIR }} && git pull'
    # - name: Rsync repo
    #   run: |
    #     ssh staging 'mkdir -p ${{ secrets.MINI_BLOOP_REMOTE_DIR }}'
    #     rsync -aPz ./ staging:${{ secrets.MINI_BLOOP_REMOTE_DIR }}

    - name: Run remote docker chain
      run: |
        ssh staging 'cd ${{ secrets.MINI_BLOOP_REMOTE_DIR }} && sudo docker-compose pull && sudo docker-compose up --force-recreate -d && sudo docker container prune -f --filter "until=24h"'
