---
name: On Pull Request

on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

jobs:
 # ent-ci:
   # runs-on: ubuntu-latest
 #   steps:
 #     - name: Checkout
  #      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
#      - name: Setup Go
 #       uses: actions/setup-go@v5
 #       with:
 #         go-version-file: 'go.mod'
  #    - name: Verify ent files
 #       uses: ent/contrib/ci@master

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: Lint
        uses: ./.github/actions/lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: Tests
        uses: ./.github/actions/tests
