---
name: release

on:
  push:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Tests
        uses: ./.github/actions/tests

  release-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate Token
        uses: actions/create-github-app-token@v1.6.1
        id: generate-token
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.APP_PRIVATE_KEY }}"

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ steps.generate-token.outputs.token }}"

  release-binaries:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate Token
        uses: actions/create-github-app-token@v1.6.1
        id: generate-token
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.APP_PRIVATE_KEY }}"

      - name: Release
        uses: ./.github/actions/go-release
        with:
          token: "${{ steps.generate-token.outputs.token }}"

  # merge-into-main:
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #       with:
  #         ref: ${{ github.event.ref }}

  #     - name: Generate Token
  #       uses: actions/create-github-app-token@v1.6.1
  #       id: generate-token
  #       with:
  #         app-id: "${{ secrets.APP_ID }}"
  #         private-key: "${{ secrets.APP_PRIVATE_KEY }}"
