---
name: release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Tests
        uses: ./.github/actions/tests

  release-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  release-binaries:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Release
        uses: ./.github/actions/go-release
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
