---
name: Schedule Snapshot

on:
  schedule:
    # Runs against the default branch every day overnight
    - cron: "18 3 * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean

env:
  DEFAULT_BRANCH: dev

jobs:
  changes-since-last:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.should-run.outputs.run }}
      latest-sha: ${{ steps.gitsha.outputs.latestsha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
      - name: Get Git SHA
        id: gitsha
        run: echo "latestsha=gitsha::$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Pull info from registry
        run: |
          docker inspect ghcr.io/${{ github.repository }}@${{ env.DEFAULT_BRANCH }}
      - name: assume-testing
        id: should-run
        run: echo "run=${{ !inputs.dryRun }}" >> $GITHUB_OUTPUT

  run-publish-snapshot:
    needs:
      - changes-since-last
    if: needs.changes-since-last.outputs.should-run == true
    uses: ./.github/workflows/publish-snapshot.yaml
    secrets: inherit
